import os
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.core.database import get_db
from app.models.agent_request import DBActionPlan
from app.models.execution_job import ExecutionJob
from app.schemas.job import ExecutionTriggerRequest, ExecutionTriggerResponse, JobStatusResponse
from app.workers.tasks import _execute_job_async_internal
from app.services.storage_service import StorageService

router = APIRouter()

@router.post("/execute", response_model=ExecutionTriggerResponse)
async def execute_job(
    req_body: ExecutionTriggerRequest,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db)
):
    """
    Triggers asynchronous sandbox execution for a verified DBActionPlan.
    """
    # 1. Fetch DBActionPlan Record
    res = await db.execute(select(DBActionPlan).where(DBActionPlan.id == req_body.plan_id))
    plan = res.scalar_one_or_none()

    if not plan:
        raise HTTPException(status_code=404, detail=f"ActionPlan with plan_id '{req_body.plan_id}' not found.")

    # 2. Create ExecutionJob ORM Record
    job = ExecutionJob(
        plan_id=plan.id,
        status="PENDING"
    )
    db.add(job)
    await db.commit()
    await db.refresh(job)

    # 3. Trigger Async Execution via FastAPI BackgroundTasks
    background_tasks.add_task(_execute_job_async_internal, job.id)

    return ExecutionTriggerResponse(
        job_id=job.id,
        status="PENDING",
        message="Job execution started."
    )

@router.get("/{job_id}", response_model=JobStatusResponse)
async def get_job_status(
    job_id: str,
    db: AsyncSession = Depends(get_db)
):
    """
    Polls the current status, execution time metrics, differential summary,
    and error logs for a specific ExecutionJob.
    """
    res = await db.execute(select(ExecutionJob).where(ExecutionJob.id == job_id))
    job = res.scalar_one_or_none()

    if not job:
        raise HTTPException(status_code=404, detail=f"ExecutionJob '{job_id}' not found.")

    return JobStatusResponse(
        job_id=job.id,
        plan_id=job.plan_id,
        status=job.status,
        execution_time_ms=job.execution_time_ms or 0,
        diff_summary=job.diff_summary,
        error_log=job.error_log,
        created_at=job.created_at
    )

@router.get("/results/{job_id}/download")
async def download_job_result(
    job_id: str,
    db: AsyncSession = Depends(get_db)
):
    """
    Downloads the transformed Excel/CSV workbook generated by a successful job execution.
    """
    res = await db.execute(select(ExecutionJob).where(ExecutionJob.id == job_id))
    job = res.scalar_one_or_none()

    if not job:
        raise HTTPException(status_code=404, detail=f"ExecutionJob '{job_id}' not found.")

    if job.status != "SUCCESS" or not job.output_file_key:
        raise HTTPException(
            status_code=400,
            detail=f"Job '{job_id}' status is '{job.status}'. Transformed file is not available."
        )

    file_path = StorageService.get_file_path(job.output_file_key)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Transformed file binary missing from disk storage.")

    filename = f"SheetPilot_Transformed_{job_id[:8]}.xlsx"
    return FileResponse(
        path=file_path,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=filename
    )
